site_name: OuterSpace Strapi-Medusa Plugins
site_url: https://strapi-medusa.outerspace.sh
site_author: Ludovic FERNANDEZ, Alien6
site_description: >-
  OuterSpace Strapi-Medusa Plugins

# Repository
repo_name: alien6-studio/outerspace-strapi-medusa
repo_url: https://github.com/Alien6-Studio/outerspace-strapi-medusa.git

# Copyright
copyright: Copyright &copy; 2024 Alien6

theme:
  name: material
  custom_dir: overrides
  logo: assets/images/logo.png
  icon:
    repo: fontawesome/brands/github-alt
  palette:
    - scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: blue grey
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
    favicon: assets/images/logo.png
  features:
    - announce.dismiss
    - announce.hide
    # - content.action.edit
    # - content.action.view
    # - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    #- toc.integrate
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html

extra:
  generator: false
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
  analytics:
    provider: google
    property: 
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.

extra_javascript:
  - javascripts/feedback.js

extra_css:
  - assets/stylesheets/extra.css

# Page tree
nav:
  - Home: index.md
  - Plugins:
    - Medusa Plugin for Strapi: plugins/medusa.md
    - Strapi Plugin for Medusa: plugins/strapi.md
  - License: license.md
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
